export const posts = [
  {
    title: "Certainly Creations",
    desc: "Clothing brand. We are open from Monday to sarturday from 8:00am to 7:00pm. Feel free to drop by.",
    img: "http://certainlycreations.paysoko.store/assets/tenant/uploads/media-uploader/certainlycreations/img-20230217-wa00091676708768.jpg",
    href: "http://certainlycreations.paysoko.store/",
    id: 1,
    category: "Fashion",
  },
  {
    title: "Baby Boo Wigs",
    desc: "We Specialized in Wig Business. We are open from Monday to sarturday from 8:00am to 7:00pm and sunday from 11:00am to 5:00pm. Feel free to drop by.",
    img: "http://babyboowigs.paysoko.store/assets/tenant/uploads/media-uploader/babyboowigs/logo-karen1676537425.jpg",
    href: "http://babyboowigs.paysoko.store/",
    id: 2,
    category: "Beauty",
  },
  {
    title: "Perfect Bikini Size",
    desc: "I deal with Women Dress Collections. We are open from Monday to sarturday from 8:00am to 7:00pm. Feel free to drop by.",
    img: "https://ke.dadasoko.com/public/uploads/all/Nw2OC1kHhiQz8aFPGGs1mQbxWlzhICzYi7DLFEf2.jpg",
    href: "https://ke.dadasoko.com/shop/Perfect-Bikini-Size-912",
    id: 3,
    category: "Fashion",
  },
  {
    title: "Dee Eye Wear",
    desc: "Dee Eye Wear is a shop of eye collection",
    img: "https://dee-eye-wear.paysoko.store/assets/tenant/uploads/media-uploader/dee-eye-wear/2ac5481c-5759-49b2-84aa-c0b9a691b6ee1678283979.jpg",
    href: "https://dee-eye-wear.paysoko.store/home",
    id: 84,
    category: "Fashion",
  },
  {
    title: "Jowam Coffee Roasters",
    desc: "WE STRIVE TO BE THE BEST From cooperative society factory where berries are washed, processed, dried and stored, we move to private and state-owned coffee millers for another level of quality assurance by hulling dried coffee beans, grading/screening by size (AA, AB, C, E, HE, PB, SB, T, TT, UG, UG1, UG2, and UG3), shape, colour and weight. They label beans according to beans source farm, cooperative, plantation or garden for ascertaining FCS domestic collector/dealer connectivity with actual farmers. We, Jowam Trading Coffee Exporters, are committed to managing health, safety and environmental (HS&amp;amp;E) matters involved in the process as an integral part of our business. It is the company policy to assure the HS&amp;amp;E integrity of our processes and facilities at all times and all places.",
    img: "https://jowamcoffeeroasters.paysoko.store/assets/tenant/uploads/media-uploader/jowamcoffeeroasters/whatsapp-image-2023-04-05-at-25525-pm1680696388.jpg",
    href: "https://jowamcoffeeroasters.paysoko.store/",
    id: 85,
    category: "Drinks",
  },
  {
    title: "Closet 13",
    desc: "Closet 13 is an online shoe store and we are all about stepping out in style. Also, we deliver country wide at a fee",
    img: "https://closet-13.paysoko.store/assets/tenant/uploads/media-uploader/closet-13/af61030d-4ce9-4e27-8246-3579396279c31678168743.jpg",
    href: "https://closet-13.paysoko.store/",
    id: 86,
    category: "Fashion",
  },
  {
    title: "Felma Technologies Limited",
    desc: "We specialized in computer and IT consumables.we are open from Monday to sarturday from 8:00am to 7:00pm. Feel free to drop by.",
    img: "http://felmatech.paysoko.store/assets/tenant/uploads/media-uploader/felmatech/screenshot-20230216-113959-samsung-internet1677137740.jpg",
    href: "http://felmatech.paysoko.store/",
    id: 4,
    category: "Appliances", //Electronics
  },
  {
    title: "Wink Flourish Creations",
    desc: "I deal with Selling of women clothes including Deras, dresses, Bags and avariety of items",
    img: "http://winkflourishcreations.paysoko.store/assets/tenant/uploads/media-uploader/winkflourishcreations/wink1677148575.jpg",
    href: "http://winkflourishcreations.paysoko.store/",
    id: 5,
    category: "Fashion",
  },
  {
    title: "Khalifa Crafted Nairobi",
    desc: "Khalifa Crafted Ltd is a leather crafting company involved in making locally tanned leather into practical items that are functional and have an impressive outlook. Spearhead by our pre eminent expert on leather Mr Ladan Khalifa , we have taken the production of quality items to a whole new level hence taking the markets by storm courtesy of our sleek products that have been proven time and again as works of art.We have designed several items, thus have a diverse product range of belts , wallets, cardholders watch straps, chequebook holders just to mention a few. We have also specialised in crafting custom made items to suit the needs of our ever growing clientele network. We solemnly deal with 100%genuine leather resulting in high quality items. Leather crafting for Khalifa Crafted fervent staff transcends the financial gains. We are passionate about offering quality products and services which are in tandem with the current needs of the market.",
    img: "http://khalifacrafted.paysoko.store/assets/tenant/uploads/media-uploader/khalifacrafted/khalifa1676963595.jpg",
    href: "http://khalifacrafted.paysoko.store/home",
    id: 6,
    category: "Fashion",
  },
  {
    title: "Mali Safi Sneakers",
    desc: "I sell both male and women shoes i.e sandals , sneakers , open shoes",
    img: "http://malisafisneakers.paysoko.store/assets/tenant/uploads/media-uploader/malisafisneakers/sneaker-logo-vector1676546244.jpg",
    href: "http://malisafisneakers.paysoko.store/",
    id: 7,
    category: "Fashion",
  },
  {
    title: "Queen Scents KE",
    desc: "I deal with Fragrance From the USA. We are open from Monday to sarturday from 8:00am to 7:00pm. Feel free to drop by.",
    img: "http://queenscent.paysoko.store/assets/tenant/uploads/media-uploader/queenscent/perfume-21676557419.jpg",
    href: "http://queenscent.paysoko.store/",
    id: 8,
    category: "Fragrances",
  },
  {
    title: "Joyce U Collection",
    desc: "I am into Fashion i.e i sell both women and men apparels i.e shoes , jackets , t-shirts",
    img: "http://joyceucollection.paysoko.store/assets/tenant/uploads/media-uploader/joyceucollection/joyce-logo11676888405.jpg",
    href: "http://joyceucollection.paysoko.store/",
    id: 9,
    category: "Fashion",
  },
  {
    title: "Beyonds Collection",
    desc: "I make different types of Ankara Bags i.e travelling bags , school bags",
    img: "http://beyondscollection.paysoko.store/assets/tenant/uploads/media-uploader/beyondscollection/bags-logo1677162245.png",
    href: "https://beyondscollection.paysoko.store/",
    id: 10,
    category: "Fashion",
  },
  {
    title: "Deo Enterprise",
    desc: "I am into Fashion , i make both women and men attire i.e dresses , shirts , Trousers",
    img: "http://deoenterprise.paysoko.store/assets/tenant/uploads/media-uploader/deoenterprise/deo-logo1676967184.jpg",
    href: "http://deoenterprise.paysoko.store/",
    id: 11,
    category: "Fashion",
  },
  {
    title: "Godliver Curio Shop",
    desc: "I deal with women Fashion including making of dresses , pants, pallazo, sandles and different types of attires.",
    img: "http://godlivercurioshop.paysoko.store/assets/tenant/uploads/media-uploader/godlivercurioshop/godliver-logo11676983135.jpg",
    href: "http://godlivercurioshop.paysoko.store/",
    id: 12,
    category: "Fashion",
  },
  {
    title: "BRB Travel Styles",
    desc: "We Deal with all traveling Bags i.e Suitcases, School Bags , Pull Bags, and Rolling Bags",
    img: "http://brbtravelstyles.paysoko.store/assets/tenant/uploads/media-uploader/brbtravelstyles/whatsapp-image-2023-02-21-at-122502-pm1677048441.jpg",
    href: "http://brbtravelstyles.paysoko.store/",
    id: 13,
    category: "Bags",
  },
  {
    title: "Kays Palet Liquor",
    desc: "Kays Palet Liquor was created as a chill out joint for both friends and individuals. It is a cool and quiet place, with very distinct features, made of palets. Our prices are unbeatable, as we look at long-term services and not just today. We have equally incorporated delivery services for those quiet days at home and still offer a sitting space at the shop. Visit us: our location is in Yukos, Kitengela, next to unique car wash, shop no. 4. Karibu Kays",
    img: "http://kayspaletliquor.paysoko.store/assets/tenant/uploads/media-uploader/kayspaletliquor/img-20230221-wa00021676966494.jpg",
    href: "http://kayspaletliquor.paysoko.store/",
    id: 14,
    category: "Drinks",
  },
  {
    title: "Junes Collection",
    desc: "I deal with Women Dress Collections. We are open from Monday to sarturday from 8:00am to 7:00pm. Feel free to drop by.",
    img: "http://junes.paysoko.store/assets/tenant/uploads/media-uploader/junes/screenshot-20230222-165348-chrome1677073505.jpg",
    href: "http://junes.paysoko.store/",
    id: 15,
    category: "Fashion",
  },
  {
    title: "Neighbourhood Butcher",
    desc: "Neighbourhood is a specialty butcher shop which seeks to serve the highest quality meat cut to customers... We got you covered.",
    img: "https://neighbourhood-butcher.paysoko.store/assets/tenant/uploads/media-uploader/neighbourhood-butcher/1bbe7cd8-ee4d-4a9a-b191-286cca7551571676549066.jpg",
    href: "https://neighbourhood-butcher.paysoko.store/",
    id: 16,
    category: "Food",
  },
  {
    title: "Mama Barka Fresh Juice",
    desc: "Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. As Mama Barka Fresh juice Plaza we got you covered when it comes to quenching your thirst",
    img: "https://mama-barka-fresh-juice.paysoko.store/assets/tenant/uploads/media-uploader/mama-barka-fresh-juice/27b4c569-8fe7-4b60-b3cb-ab79793ddc7a1677151877.jpg",
    href: "https://mama-barka-fresh-juice.paysoko.store/",
    id: 17,
    category: "Drinks",
  },
  {
    title: "Haziya Enterprise",
    desc: "A home of freshly packed and unpacked fruits and vegetables. we got you covered when it comes to your grocery shopping",
    img: "https://haziya-enterprise.paysoko.store/assets/tenant/uploads/media-uploader/haziya-enterprise/34b5a2e0-787b-4470-815b-8121f3e66f1a1677067228.jpg",
    href: "https://haziya-enterprise.paysoko.store/",
    id: 18,
    category: "Groceries",
  },
  {
    title: "Alexo Beauty",
    desc: "AlexoBeauty is a place to be. we offer the best services to our esteemed customers. We are located at Laving-ton west-field mall, first floor shop number B40. Our mission is to offer our customers with the best services any day any time. We are open from Monday - Friday at 8:00 AM - 7:00 PM on weekdays and on weekends we are open on Saturday from 9:00 AM - 5:00 PM. Sundays we do bookings only",
    img: "https://worksoko.com/assets/uploads/media-uploader/09142f89-6edf-48d4-9258-15f5d280b8741676873982.jpg",
    href: "https://worksoko.com/ALEXOBEAUTY",
    id: 19,
    category: "Beauty",
  },
  {
    title: "Dicardo Wears",
    desc: "DICARDO WEARS is a sneaker palace established 2023 February.. owned by Mark Oduor Oduor alias DICARDO born and raised in ruaraka Its an online active shop dealing with a variety of sneakers at an affordable price examples are Jordans,casual wears,official wears,nikes, addidas,puma and many more. With everything we have we got your looks and style covered ... Delivery is done all around kenya on charges.",
    img: "https://dicardo-wears.paysoko.store/assets/tenant/uploads/media-uploader/dicardo-wears/f775ac87-ad75-44f3-a4d9-fdfd5e758f5d1676459413.jpg",
    href: "https://dicardo-wears.paysoko.store/",
    id: 20,
    category: "Fashion",
  },
  {
    title: "Kitchen & Lighting Kenya",
    desc: "We sell quality kitchen households and lightings. we are located in Naivasha along biashara street opposite naivas kubwa supermarket. we got you covered when it comes to all house lightings and kitchen accessories",
    img: "https://kitchens-and-lighting-kenya254.paysoko.store/assets/tenant/uploads/media-uploader/kitchens-and-lighting-kenya254/1d36b93d-7552-4a3d-9ccb-674c3a54e6e61676539559.jpg",
    href: "https://kitchens-and-lighting-kenya254.paysoko.store/",
    id: 21,
    category: "Appliances", //Electronics
  },
  {
    title: "Purity Nails",
    desc: "we are located at Hurlingham Lenana Arcade shop no 6. we are open from Monday to sarturday from 8:00am to 7:00pm. Feel free to drop by.",
    img: "https://worksoko.com/assets/uploads/media-uploader/00e30596-b315-4ff2-a09e-1727743c51291676886978.jpg",
    href: "https://worksoko.com/puritynails",
    id: 22,
    category: "Beauty",
  },
  {
    title: "Colony Couture",
    desc: "We are about Luxury leather accessories brand. we are open from Monday to sarturday from 8:00am to 7:00pm. Feel free to drop by.",
    img: "https://colony-couture.paysoko.store/assets/tenant/uploads/media-uploader/colony-couture/d2cc4f62-57ac-486a-aa86-470104c069b41676899373.jpg",
    href: "https://colony-couture.paysoko.store/",
    id: 23,
    category: "Fashion",
  },
  {
    title: "Love Shark Books",
    desc: "Love shark we are all about mind blowing and mind opening books.we are open from Monday to sarturday from 8:00am to 7:00pm. Feel free to drop by.",
    img: "https://love-shark-books.paysoko.store/assets/tenant/uploads/media-uploader/love-shark-books/7ec9765b-f889-4903-a046-20db7e97bee31676972193.jpg",
    href: "https://love-shark-books.paysoko.store/",
    id: 24,
    category: "Books",
  },
  {
    title: "Coastal Treats",
    desc: "Coastal treats started because I wanted to give people the best of Coastal snacks(candies) Mabuyu are made from Baobab seeds as you enjoy the sweet snack you get the benefits of baobab fruits…! Achari are dried mango coated with baobab powder easy to snack as you go ! So far coastal treats have three employees and we are going to grow and employ more people",
    img: "https://coastal-treats.paysoko.store/assets/tenant/uploads/media-uploader/coastal-treats/img-09181676967384.jpg",
    href: "https://coastal-treats.paysoko.store/",
    id: 25,
    category: "Food",
  },
  {
    title: "Forever Living Products",
    desc: "Forever Living are the largest growers,manufacturers and distributors of Aloe Vera.we are open for bookings from Monday to sarturday from 8:00am to 7:00pm. Feel free to drop by.",
    img: "http://foreverliving.paysoko.store/assets/tenant/uploads/media-uploader/foreverliving/e39dcb87-7a58-44a9-a013-d85c5be21c421677072085.jpg",
    href: "http://foreverliving.paysoko.store/",
    id: 26,
    category: "Beauty",
  },
  {
    title: "Kiya Beauty",
    desc: "We are located at Nairobi Kilimani Souk Avenue ground flour shop number 6 We are open for bookings from Monday to Saturday 9:00am and evening time depending with the client On Sundays we open on appointment. Kiyas Beauty Saloon is also open for bookings during Holidays Our mission is to serve our clients with love and care.",
    img: "https://worksoko.com/assets/uploads/media-uploader/b2db60dc-54f5-452d-abc7-86199c4cfd091676880787.jpg",
    href: "https://worksoko.com/Kiya%20Beuty%20Salon",
    id: 27,
    category: "Beauty",
  },
  {
    title: "Stisyl Fashion",
    desc: "",
    img: "http://stisyl-fashion.paysoko.store/assets/tenant/uploads/media-uploader/stisyl-fashion/img-20230112-wa00011676468971.jpg",
    href: "http://stisyl-fashion.paysoko.store/shop",
    id: 28,
    category: "Beauty",
  },
  {
    title: "The Fade Room",
    desc: "We are located in Ongata Rongai opposite lunar petrol station The fade Room mission is to change the haircut game and design we are designed to fit todays on-demand lifestyle and offer you remarkably easy way to experience a haircut by our best barbers and stylists. Do your bookings as from 7:00am to 8:00pm and enjoy the best services in town.",
    img: "https://worksoko.com/assets/uploads/media-uploader/c41dc879-f7af-483c-977c-540148f509e81676888025.jpg",
    href: "https://worksoko.com/The%20Fade%20Room",
    id: 29,
    category: "Beauty",
  },
  {
    title: "Fatima Fashion",
    desc: "we are open from Monday to Saturday 9:00am to 6:00pm. We are located in Mombasa Likoni area. Our vission as a fashion shop is to deliver the best.",
    img: "http://fatima.paysoko.store/assets/tenant/uploads/media-uploader/fatima/istockphoto-885789004-1024x10241676536345.jpg",
    href: "http://fatima.paysoko.store/",
    id: 30,
    category: "Fashion",
  },
  {
    title: "Prince Creative",
    desc: "Prince Creative Studio photography is cheerful and fun, creating a lasting impression in the mind of a visitor and everybody willing to shoot with us. We are flexible for bookings across the country but we are based in Nairobi. For any inquiries feel free to contact us through the Number below +254 701 733 235",
    img: "https://worksoko.com/assets/uploads/media-uploader/bebd714d-557e-4e25-ad18-72e3e3b035371676963437.jpg",
    href: "https://worksoko.com/Prince%20creative",
    id: 31,
    category: "Photography",
  },
  {
    title: "The One Hair",
    desc: "We are located in Nairobi Lavington Green Mall. our purpose is to make you glow and look extra good with our hair we deliver with a lot of love to our clients and our vision is to grow globally and deliver the best. Or shop is open from 10:00am to 6:00pm in the evening.",
    img: "http://the-one-hair.paysoko.store/assets/tenant/uploads/media-uploader/the-one-hair/93f2a95e-f358-483a-818a-f015a03c71dd1677052755.jpg",
    href: "http://the-one-hair.paysoko.store/",
    id: 32,
    category: "Beauty",
  },
  {
    title: "Ebenezer Embroidery",
    desc: "We started our sewing in a kibanda which wasn't permanent but we had a strong believe that we are moving and we gonna grow big one day. Now we have a physical store with two employees and we are looking forward in growing big and more creative. We are open from Monday to Saturday from 9:00am to 6:00pm in the evening.",
    img: "http://embroidery-designs.paysoko.store/assets/tenant/uploads/media-uploader/embroidery-designs/il-fullxfull4192367035-sp2o1676965878.jpg",
    href: "http://embroidery-designs.paysoko.store/home",
    id: 33,
    category: "Appliances", //Appliances
  },
  {
    title: "Emily Food Mart",
    desc: "We are open for bookings from Monday to Saturday as from 9:00am to 6:00pm. We are located in Mombasa Likoni area Our vission as emily's food mart is to grow big and deliver the best to our clients.",
    img: "http://emilys-food-mart.paysoko.store/assets/tenant/uploads/media-uploader/emilys-food-mart/images-91677134685.jpg",
    href: "http://emilys-food-mart.paysoko.store/home",
    id: 34,
    category: "Food",
  },
  {
    title: "Mjj Collection",
    desc: "Mjj collection started as a online shop and with time we managed to get a physical store. we have really grown big in terms of business within a aperiod of one year. we are located at kitengela near club nomads . we are looking forward to serve our clients with love and care. Feel free to order with us from monday to sarturdays 9:00am to 8:00pm . On holidays our physical store is always closed.",
    img: "http://m-j-j-collection.paysoko.store/assets/tenant/uploads/media-uploader/m-j-j-collection/download1677139383.jpg",
    href: "http://m-j-j-collection.paysoko.store/home",
    id: 35,
    category: "Fashion",
  },
  {
    title: "Jofibz Cakes & Goodies",
    desc: "We are located in Nairobi Kariobangi South. we are open for bookings from Monday to sarturday from 8:00am to 7:00pm. Feel free to bake with us for the best taste.",
    img: "http://jofibzcakesandgoodies.paysoko.store/assets/tenant/uploads/media-uploader/jofibzcakesandgoodies/download1677151996.jpg",
    href: "http://jofibzcakesandgoodies.paysoko.store/",
    id: 36,
    category: "Food",
  },
  {
    title: "Clinton Collection",
    desc: "We are an online ENTITY located in KISUMU We sell a variety of ready made clothes and SHOES Call us via 0706305348 for inquiries or to place an order🤗 Deliveries in and out of Kisumu Town at a small fee Returns or exchange available 48hrs after delivery NO REFUNDS.",
    img: "http://clintoncollection.paysoko.store/assets/tenant/uploads/media-uploader/clintoncollection/image-111666508652.png",
    href: "http://clintoncollection.paysoko.store/",
    id: 37,
    category: "Fashion",
  },
  {
    title: "Zarino Kids Store",
    desc: "Zarino Kids Store is a leading virtual kids store that brings you all the kid items birthday suppliers, party decorations, Educational board, Protective gears and helmets, Kitchen sets, Swimming gears, Themed costumes,Floaters and many more. We sell our products at very affordable prices.",
    img: "https://zarinokidzstore.paysoko.store/assets/tenant/uploads/media-uploader/zarinokidzstore/whatsapp-image-2023-02-23-at-1247361677148734.jpg",
    href: "https://zarinokidzstore.paysoko.store/",
    id: 38,
    category: "Kids",
  },
  {
    title: "Jos Fabricators",
    desc: "We are a fabricator company that has various designs to different items and we ensure that we exceed customer's expectations by having good quality items.",
    img: "https://josfabricators.paysoko.store/assets/tenant/uploads/media-uploader/josfabricators/logo1677137128.jpg",
    href: "https://josfabricators.paysoko.store/",
    id: 39,
    category: "Appliances", //appliances
  },
  {
    title: "Fumani Co.",
    desc: "Fumani is a luxury skin care and hair care brand that seeks to better the appearance of skin and hair by its products that are cruelty free and made with love",
    img: "https://fumanico.paysoko.store/assets/tenant/uploads/media-uploader/fumanico/logo11676979653.jpg",
    href: "https://fumanico.paysoko.store/",
    id: 40,
    category: "Beauty",
  },
  {
    title: "Infinit Kicks",
    desc: "Infinit kicks is a footwear store for quality and easygoing shoes from many brands. We got style for ladies and men. We started one year ago having a physical shop but initially we were an online shop marketing and advertising on social media platforms. Our mail goal is Customer satisfaction. Shoe manufacturing is no exception. Obtaining feedback on sales is part of achieving this goal. Knowing which products produce the most sales is a clear indicator of what types of shoes the customer base prefer. Increasing customer retention, ecommerce sales and community involvement is one of our goals as well. Our mission is to offer our customers with a footwear product that has desirable performance and attributes such as impeccable quality, enhanced features, comfort and its diverse assortment of trending styles and exclusive designs.",
    img: "https://infinitkicks.paysoko.store/assets/tenant/uploads/media-uploader/infinitkicks/whatsapp-image-2023-02-17-at-0842191676829382.jpg",
    href: "https://infinitkicks.paysoko.store/",
    id: 41,
    category: "Fashion",
  },
  {
    title: "Eddy Poultry",
    desc: "We sell genuine eggs at affordable prices and we ensure that delivery is done to our customers despite the location.",
    img: "https://eddypoultryshop.paysoko.store/assets/tenant/uploads/media-uploader/eddypoultryshop/images-11676920856.jpg",
    href: "https://eddypoultryshop.paysoko.store/",
    id: 42,
    category: "Food",
  },
  {
    title: "Queens Collection",
    desc: "Queen's collections is a lifestyle retailer dedicated to inspiring customers through a unique combination of product, creativity and cultural understanding. Founded in 2021, Queen's Collections operates in Mombasa, with a dream of retailing worldwide to offer a well curated mix of women's and men's product assortments. We exist to create experiences where fashion, culture and purpose come together.",
    img: "http://queenscollection.paysoko.store/assets/tenant/uploads/media-uploader/queenscollection/whatsapp-image-2023-02-16-at-1935131676570943.jpg",
    href: "http://queenscollection.paysoko.store/",
    id: 43,
    category: "Fashion",
  },
  {
    title: "Purity Shop",
    desc: "We are an online shop that sells clothes. We are open from Monday to sarturday from 8:00am to 7:00pm. Feel free to drop by.",
    img: "https://purityshop.paysoko.store/assets/tenant/uploads/media-uploader/purityshop/download-11677057193.png",
    href: "https://purityshop.paysoko.store/",
    id: 44,
    category: "Fashion",
  },
  {
    title: "Coffee Klub",
    desc: "We are an online shop that deals with good quality coffee and skin care products.",
    img: "https://coffeeklub.paysoko.store/assets/tenant/uploads/media-uploader/coffeeklub/whatsapp-image-2023-02-15-at-1603571676466336.jpg",
    href: "https://coffeeklub.paysoko.store/",
    id: 45,
    category: "Drinks",
  },
  {
    title: "Fabhq Beauty",
    desc: "We are a beauty shop located in Hurlingham along Lenana Road at Lenana Mall shop no.8 We open the shop at 8am till late from Monday to Saturday and 12 noon till late on Sunday We offer nail services and massage all available att our shop. We do house calls at a cost depending on where the customer is and during the house calls we carry all our equipments unless the customer says otherwise. We exist to create experiences where beauty and comfort come together.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-02-17-at-14505121676879449.jpeg",
    href: "https://worksoko.com/John%20Bosco%20Boyo",
    id: 46,
    category: "Beauty",
  },
  {
    title: "Laundry Depot",
    desc: "Laundry Depot is located in Kilimani at b_Arcade Mall First Floor. We are open every day of the week from 8 AM to 7PM We exist to give quality and affordable laundry services.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-02-10-at-1236321676886017.jpeg",
    href: "https://worksoko.com/Laundry%20Depot",
    id: 47,
    category: "Laundry",
  },
  {
    title: "The Brow & Lash Wispy",
    desc: "The browandlashwispy is a brand that offers top eyebrow and eyelash services for the beautification and utmost satisfaction of its clients.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-02-20-at-1705341677047459.jpeg",
    href: "https://worksoko.com/Francisca%20Kibulo",
    id: 48,
    category: "Beauty",
  },
  {
    title: "Karol Apparels",
    desc: "We deal with Everything Men's Collection, casual wear,office wear and accessories.",
    img: "http://karolapparels.paysoko.store/assets/tenant/uploads/media-uploader/karolapparels/img-20230228-wa00451677571674.jpg",
    href: "http://karolapparels.paysoko.store/home",
    id: 49,
    category: "Fashion",
  },
  {
    title: "Trish Fashions",
    desc: "We Are specialized in Women attire i.e clothes, shoes",
    img: "http://trishfashions.paysoko.store/assets/tenant/uploads/media-uploader/trishfashions/trish1677493173.jpg",
    href: "http://trishfashions.paysoko.store/home",
    id: 50,
    category: "Fashion",
  },
  {
    title: "Madacha Enterprise",
    desc: "We deal with both commercial and residential properties",
    img: "http://madechaenterprises.paysoko.store/assets/tenant/uploads/media-uploader/madechaenterprises/ml1677501664.jpg",
    href: "http://madechaenterprises.paysoko.store/home",
    id: 51,
    category: "Housing",
  },
  {
    title: "Gentlemen Quotas",
    desc: "We deal with Both Men and Women Collection",
    img: "http://gq-gentlemen-quotas.paysoko.store/assets/tenant/uploads/media-uploader/gq-gentlemen-quotas/screenshot-20230228-163033-gbwhatsapp1677590517.jpg",
    href: "http://gq-gentlemen-quotas.paysoko.store/home",
    id: 52,
    category: "Fashion",
  },
  {
    title: "Pretty Fabric & Holstery",
    desc: "We specialized in selling, making of unique furniture and holstery tools including Sofasets , Tables, Chairs to fit our customer preferences",
    img: "http://prettyfabholstery.paysoko.store/assets/tenant/uploads/media-uploader/prettyfabholstery/screenshot-20230227-105412-chrome1677484125.jpg",
    href: "http://prettyfabholstery.paysoko.store/home",
    id: 53,
    category: "Furniture",
  },
  {
    title: "Catchy Footsteps",
    desc: "I sell all kind of Sneakers. Drop by anytime from 8am to 7pm",
    img: "http://catchyfootsteps.paysoko.store/assets/tenant/uploads/media-uploader/catchyfootsteps/screenshot-20230228-170642-chrome1677592679.jpg",
    href: "http://catchyfootsteps.paysoko.store/home",
    id: 54,
    category: "Fashion",
  },
  {
    title: "Jibu Barber Shop & Spa",
    desc: "we are located at west-filed mall shop no 15 at hurlingham",
    img: "https://worksoko.com/assets/uploads/media-uploader/massage-photo-alofoq-spa1677484276.jpg",
    href: "https://worksoko.com/KENDI",
    id: 55,
    category: "Beauty",
  },
  {
    title: "Paris Home Decor",
    desc: "Paris Home decor got you covered with the best home quality affordable decors. we are located at lavington the curve mall",
    img: "https://paris-home-decor.paysoko.store/assets/tenant/uploads/media-uploader/paris-home-decor/0a7b5197-3bf4-4419-87c1-4c8cdfcdffad1677579972.jpg",
    href: "https://paris-home-decor.paysoko.store/home",
    id: 59,
    category: "Appliances",
  },
  {
    title: "Alpha Barber Shop",
    desc: "We are located at West field Hub around kilimani. Drop by at any time from 8am to 9pm",
    img: "https://worksoko.com/assets/uploads/media-uploader/80cd353f-1bc7-499e-a083-c6380bad9e3e1677574115.jpg",
    href: "https://worksoko.com/Martin%20Habimana",
    id: 56,
    category: "Barbershop",
  },
  {
    title: "Bi Mas Salon",
    desc: "we are located at kabwagi in Karen. Drop by at any time from 8am to 7pm",
    img: "https://worksoko.com/assets/uploads/media-uploader/e72c2dbb-c8a7-46f5-9c4e-cb222a42cd211677226700.jpg",
    href: "https://worksoko.com/Esther%20Koimburi",
    id: 57,
    category: "Beauty",
  },
  {
    title: "LuxBix Motors",
    desc: "",
    img: "https://luxbiz-motors.paysoko.store/assets/tenant/uploads/media-uploader/luxbiz-motors/ffa8c5df-6e12-4b9b-98c1-5babda0e68db1676900840.jpg",
    href: "https://luxbiz-motors.paysoko.store/home",
    id: 58,
    category: "Cars",
  },
  {
    title: "Red Rose Salon",
    desc: "we are located at kileleshwa olenguruone rd 75. Drop by at any time from 8am to 6pm",
    img: "https://worksoko.com/assets/uploads/media-uploader/34f1d148-de0c-4a5f-85a3-95d432e085251677501918.jpg",
    href: "https://worksoko.com/saloonist",
    id: 60,
    category: "Beauty",
  },
  {
    title: "Ann's Hair & Beauty Salon",
    desc: "We are located at Mombasa likoni area. Drop by at any time from 8am to 7pm",
    img: "https://worksoko.com/assets/uploads/media-uploader/a0bc1dfd-c2be-430d-ba64-4ad633815a1b1677490453.jpg",
    href: "https://worksoko.com/ANN",
    id: 61,
    category: "Beauty",
  },
  {
    title: "Versatile Beads",
    desc: "Versatile beads sells quality jewelry for affordable prices. We ensure we exceed the customers expectations and ensure they get value for their money. Delivery can be done in different places at a cost.",
    img: "https://versatilebeads.paysoko.store/assets/tenant/uploads/media-uploader/versatilebeads/whatsapp-image-2023-02-23-at-174749-11677182098.jpg",
    href: "https://versatilebeads.paysoko.store/home",
    id: 62,
    category: "Jewelry",
  },
  {
    title: "Jacky's Salon",
    desc: "",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-02-23-at-1552171677503454.jpeg",
    href: "https://worksoko.com/Jacky%20Atieno",
    id: 63,
    category: "Beauty",
  },
  {
    title: "Prime Look Hair & Beauty Salon",
    desc: "",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-02-27-at-0952311677486118.jpeg",
    href: "https://worksoko.com/Alvin%20Prime",
    id: 64,
    category: "Beauty",
  },
  {
    title: "Anne Wambui",
    desc: "The salon is located in Hurlingham , Nyaku House First Floor and we offer beauty services as manicure and pedicure and also salon services like weaving, washing and treatment. We also sell hundred percent human hair with different inches, color and texture.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-02-28-at-1603481677592589.jpeg",
    href: "https://worksoko.com/Ann%20Wambui",
    id: 65,
    category: "Beauty",
  },
  {
    title: "Mama Fidel Juice Parlour",
    desc: "Mama Fidel is a juice parlour located in Kiwerera, Pwani region and started with selling very small portions of juice depending on what the customer could afford. We can now afford to make more litres of different type of juices. We still sell juices depending on customer's affordability.",
    img: "https://mamafideljuiceparlour.paysoko.store/assets/tenant/uploads/media-uploader/mamafideljuiceparlour/juice-21677568175.jpg",
    href: "https://mamafideljuiceparlour.paysoko.store/home",
    id: 66,
    category: "Drinks",
  },
  {
    title: "Peqim Technologies Limited",
    desc: "Peqim Technologies Limited is an ICT Company operating in Kenya and located in Mombasa, providing customized telecommunication and surveillance solutions for business and also home based needs. The company has been in business for the last 5 years and has bank of experienced technicians offering solutions specifically tailored to client requirements. The company s strength lies in its ability to deliver precise solutions to clients at competitive costs backed by excellent Customer Service.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-02-27-at-0956581677481056.jpeg",
    href: "https://worksoko.com/Humphrey%20Pembe%20Jacob",
    id: 67,
    category: "Appliances",
  },
  {
    title: "Green Delight Juice Bar",
    desc: "Green delight juice bar is located in Nairobi Gigiri area at Box park stall no.1B We strive to give the best healthy juices with a wide variety and ensure we sell the best at affordable prices.",
    img: "https://greendelightjuicebar.paysoko.store/assets/tenant/uploads/media-uploader/greendelightjuicebar/whatsapp-image-2023-03-15-at-1805591678952700.jpg",
    href: "https://greendelightjuicebar.paysoko.store/",
    id: 68,
    category: "Drinks",
  },
  {
    title: "Viren Collections",
    desc: "Viren collection is a store that deals with home improvement, home fragrance and interior. We strive to sell the best products at affordable prices.",
    img: "https://virencollection.paysoko.store/assets/tenant/uploads/media-uploader/virencollection/whatsapp-image-2023-03-14-at-1004181678777723.jpg",
    href: "https://virencollection.paysoko.store/",
    id: 69,
    category: "Appliances",
  },
  {
    title: "Natvens",
    desc: "Natvens we are a home of cereal made with love packed with yummy goodness",
    img: "https://natvens.paysoko.store/assets/tenant/uploads/media-uploader/natvens/998693e1-04f8-4b1e-87be-cf514a0984dd1677744943.jpg",
    href: "https://natvens.paysoko.store/home",
    id: 70,
    category: "Food",
  },
  {
    title: "Tito Fresh Grocery",
    desc: "Only fresh produce here we got you covered with all your vegetables and fruits",
    img: "https://tito-fresh-grocery-shop.paysoko.store/assets/tenant/uploads/media-uploader/tito-fresh-grocery-shop/34b5a2e0-787b-4470-815b-8121f3e66f1a1677750467.jpg",
    href: "https://tito-fresh-grocery-shop.paysoko.store/home",
    id: 71,
    category: "Food",
  },
  {
    title: "Jackson Taste and Fun",
    desc: "This package consists of the following grilled chicken, beef stew, pilau/vegetable rice, chapati, fried njahi, mukimo, mixed vegetables, watermelon/pineapple.This package goes for Ksh.825 per plate.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-03-01-at-1059271677663499.jpeg",
    href: "https://worksoko.com/Jackson%20Githua",
    id: 72,
    category: "Food",
  },
  {
    title: "Ray Nails254",
    desc: "Overlays are a coating of a very thin layer of acrylic or gel products applied on top of natural nail without the need to extend.Anything that is applied on top of your natural nails will be considered an overlay.This will give you greater strength in aiding your nails to gain natural growth.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-03-01-at-1318171677672377.jpeg",
    href: "https://worksoko.com/Regina%20Ndihiu",
    id: 73,
    category: "Beauty",
  },
  {
    title: "Bensuthebeautician",
    desc: "A pedicure is a comprehensive treatment of your feet and is suitable for both men and women.It involves cutting, trimming and shaping your toenails, tending to your cuticles, exfoliating, hydrating and massaging your feet, and, if desired, painting your toenails.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-03-01-at-163527-11677824524.jpeg",
    href: "https://worksoko.com/Rose%20Nandwa",
    id: 74,
    category: "Beauty",
  },
  {
    title: "Joses Shoe Plaza",
    desc: "Joses Shoes Plaza is an online business that strives to sell quality shoes at affordable prices and ensure we exceed our customers expectations. We also do deliveries to our customers preference.",
    img: "https://joseshoeplaza.paysoko.store/assets/tenant/uploads/media-uploader/joseshoeplaza/whatsapp-image-2023-03-01-at-0944581677737776.jpg",
    href: "https://joseshoeplaza.paysoko.store/home",
    id: 75,
    category: "Fashion",
  },
  {
    title: "Muriithi Grocery",
    desc: "Muriithi Grocery deals with selling watermelon, banana and mangoes. We sell both on retail and wholesale and ensure that we meet all our customers needs. We strive to give the best produce at affordable prices.",
    img: "https://muriithigrocery.paysoko.store/assets/tenant/uploads/media-uploader/muriithigrocery/fruit-logo1677756703.jpg",
    href: "https://muriithigrocery.paysoko.store/",
    id: 76,
    category: "Food",
  },
  {
    title: "Cindy Nails",
    desc: "Tips are lightweight 'nail'-shaped plastic plates glued on the end of the natural nail; forms are shaped sheets with a sticky edge that is effectively attached to the tip of the finger and wrapped around the entirety of the nail.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-03-02-at-161430-11677826289.jpeg",
    href: "https://worksoko.com/Lucy%20Sydney",
    id: 77,
    category: "Beauty",
  },
  {
    title: "Trimaxx Ventures",
    desc: "",
    img: "https://trimaxxventuresltd.paysoko.store/assets/tenant/uploads/media-uploader/trimaxxventuresltd/whatsapp-image-2023-03-03-at-101538-11677829713.jpg",
    href: "https://trimaxxventuresltd.paysoko.store/",
    id: 78,
    category: "Appliances",
  },
  {
    title: "Carina Fancy Creations",
    desc: "Crocs, the easy choice for the active lifestyle",
    img: "https://carinabeauty.paysoko.store/assets/tenant/uploads/media-uploader/carinabeauty/whatsapp-image-2023-03-03-at-120601-11677845087.jpg",
    href: "https://carinabeauty.paysoko.store/",
    id: 79,
    category: "Fashion",
  },
  {
    title: "Joyran Charcoal Dealers",
    desc: "Joyran Charcoal Dealers sells good quality charcoal and firewood from indeginious trees that ensure the customer benefits fully from buying from us by how the products are going to serve them.",
    img: "https://joyrancharcoaldealers.paysoko.store/assets/tenant/uploads/media-uploader/joyrancharcoaldealers/logo1677747047.jpg",
    href: "https://joyrancharcoaldealers.paysoko.store/",
    id: 80,
    category: "Appliances",
  },
  {
    title: "Sprouts Salon",
    desc: "Gels can hold moisture and protect the hair, enhance and define curls, lengthen the hair, style hair into place, control frizz, create a flexible hold, add body and shine, provide help with manageability of the hair and provide a smooth comb through.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-03-06-at-0924071678084430.jpeg",
    href: "https://worksoko.com/Esabela%20Kweti",
    id: 81,
    category: "Beauty",
  },
  {
    title: "Rita Nyce Salon",
    desc: "The line where the fabric pieces will be stitched together. When matching up pattern pieces or making pattern adjustments, it is essential to match or adjust the stitching line, not the cutting edge",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-03-06-at-100213-11678086903.jpeg",
    href: "https://worksoko.com/Nancy%20Mbogo",
    id: 82,
    category: "Beauty",
  },
  {
    title: "TreasureSalon",
    desc: "While this style can last up to several weeks, leaving locs in longer than what's suggested can lead to oil buildup, resulting in damage to your hair and scalp, so it's best not to keep them in longer than eight weeks.",
    img: "https://worksoko.com/assets/uploads/media-uploader/whatsapp-image-2023-03-06-at-1118181678091315.jpeg",
    href: "https://worksoko.com/Dorothy%20Gila",
    id: 83,
    category: "Beauty",
  },

  //   { title: "", desc: "", img: "", href: "", id: 87, category: "" },
  //   { title: "", desc: "", img: "", href: "", id: 88, category: "" },
  //   { title: "", desc: "", img: "", href: "", id: 89, category: "" },
];

export const categories = [
  { id: 1, name: "All" },
  { id: 4, name: "Fashion" },
  { id: 3, name: "Fragrances" },
  { id: 5, name: "Beauty" },
  { id: 6, name: "Bags" },
  { id: 7, name: "Drinks" },
  { id: 9, name: "Food" },
  { id: 8, name: "Appliances" },
  { id: 10, name: "Books" },
];
